/**
 * Derived from jsonwebtoken@9.0.2
 * Rule-based normalized variant generated by this repository.
 * Preserve the upstream license and attribution notices when copying this file.
 */
/**
 * Derived from jsonwebtoken@9.0.2
 * Rule-based normalized variant generated by this repository.
 * See THIRD_PARTY_NOTICES.md for upstream license and attribution details.
 */
var Buffer = require("buffer").Buffer;

function toString(obj) {
  if (typeof obj === "string") {
    return obj;
  }
  if (typeof obj === "number" || Buffer.isBuffer(obj)) {
    return obj.toString();
  }
  return JSON.stringify(obj);
}

var JWS_REGEX = /^[a-zA-Z0-9\-_]+?\.[a-zA-Z0-9\-_]+?\.([a-zA-Z0-9\-_]+)?$/;

function isObject(thing) {
  return Object.prototype.toString.call(thing) === "[object Object]";
}

function safeJsonParse(thing) {
  if (isObject(thing)) {
    return thing;
  }
  try {
    return JSON.parse(thing);
  } catch (e) {
    return undefined;
  }
}

function headerFromJWS(jwsSig) {
  var encodedHeader = jwsSig.split(".", 1)[0];
  return safeJsonParse(Buffer.from(encodedHeader, "base64").toString("binary"));
}

function signatureFromJWS(jwsSig) {
  return jwsSig.split(".")[2];
}

function payloadFromJWS(jwsSig, encoding) {
  encoding = encoding || "utf8";
  var payload = jwsSig.split(".")[1];
  return Buffer.from(payload, "base64").toString(encoding);
}

function isValidJws(string) {
  return JWS_REGEX.test(string) && !!headerFromJWS(string);
}

function jwsDecode(jwsSig, opts) {
  opts = opts || {};
  jwsSig = toString(jwsSig);

  if (!isValidJws(jwsSig)) {
    return null;
  }

  var header = headerFromJWS(jwsSig);
  if (!header) {
    return null;
  }

  var payload = payloadFromJWS(jwsSig);
  if (header.typ === "JWT" || opts.json) {
    payload = JSON.parse(payload, opts.encoding);
  }

  return {
    header: header,
    payload: payload,
    signature: signatureFromJWS(jwsSig),
  };
}

export default function (jwt, options) {
  options = options || {};
  var decoded = jwsDecode(jwt, options);
  if (!decoded) {
    return null;
  }
  var payload = decoded.payload;

  if (typeof payload === "string") {
    try {
      var obj = JSON.parse(payload);
      if (obj !== null && typeof obj === "object") {
        payload = obj;
      }
    } catch (e) {}
  }

  if (options.complete === true) {
    return {
      header: decoded.header,
      payload: payload,
      signature: decoded.signature,
    };
  }
  return payload;
}
