/**
 * Derived from isarray@2.0.5
 * Rule-based normalized variant generated by this repository.
 * Preserve the upstream license and attribution notices when copying this file.
 */
/**
 * Derived from isarray@2.0.5
 * Rule-based normalized variant generated by this repository.
 * See THIRD_PARTY_NOTICES.md for upstream license and attribution details.
 */
var toString = {}.toString;

export default Array.isArray ||
  function (arr) {
    return toString.call(arr) == "[object Array]";
  };
