import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

import { parse, print, types } from "recast";
import babelParser from "recast/parsers/babel.js";

const { builders: b, namedTypes: n, visit } = types;

const NORMALIZED_HEADER_PATTERN =
  /^\/\*\*\n \* Derived from .+?\n \* Rule-based normalized variant generated by this repository\.\n \* Preserve the upstream license and attribution notices when copying this file\.\n \*\/\n\n/s;

export function normalizeCommonJsToEsm(source) {
  const ast = parse(source, { parser: babelParser });
  let transformed = false;

  visit(ast, {
    visitExpressionStatement(currentPath) {
      const expression = currentPath.node.expression;

      if (
        n.AssignmentExpression.check(expression) &&
        expression.operator === "=" &&
        n.MemberExpression.check(expression.left) &&
        !expression.left.computed &&
        n.Identifier.check(expression.left.object) &&
        expression.left.object.name === "module" &&
        n.Identifier.check(expression.left.property) &&
        expression.left.property.name === "exports"
      ) {
        transformed = true;
        currentPath.replace(b.exportDefaultDeclaration(expression.right));
        return false;
      }

      this.traverse(currentPath);
    },
  });

  if (!transformed) {
    throw new Error("No supported CommonJS default export found.");
  }

  return print(ast, { tabWidth: 2 }).code;
}

export function buildNormalizedHeader(meta) {
  return [
    "/**",
    ` * Derived from ${meta.sourcePackage}@${meta.sourceVersion}`,
    " * Rule-based normalized variant generated by this repository.",
    " * Preserve the upstream license and attribution notices when copying this file.",
    " */",
    "",
  ].join("\n");
}

export function withNormalizedHeader(source, meta) {
  const withoutExistingHeader = source.replace(NORMALIZED_HEADER_PATTERN, "");
  return `${buildNormalizedHeader(meta)}${withoutExistingHeader}`;
}

export async function normalizeSnippet(slug, root = process.cwd()) {
  const snippetDir = path.join(root, "snippets", slug);
  const inputPath = path.join(snippetDir, "raw.js");
  const outputPath = path.join(snippetDir, "normalized.ts");
  const metaPath = path.join(snippetDir, "meta.json");
  const source = await readFile(inputPath, "utf8");
  const meta = JSON.parse(await readFile(metaPath, "utf8"));
  const normalized = withNormalizedHeader(normalizeCommonJsToEsm(source), meta);

  await mkdir(snippetDir, { recursive: true });
  await writeFile(outputPath, normalized, "utf8");

  return path.relative(root, outputPath);
}

async function main() {
  const slug = process.argv[2];

  if (!slug) {
    throw new Error("Usage: bun run normalize:snippet <slug>");
  }

  const outputPath = await normalizeSnippet(slug);
  process.stdout.write(`Normalized ${slug} -> ${outputPath}\n`);
}

const isDirectRun =
  process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href;

if (isDirectRun) {
  main().catch((error) => {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exit(1);
  });
}
